public void testIssue108() {
    try{
        //execjs.eval("function assert(b) {if (!b) throw 'error'} assert(f() === 1) var f = function() {return 2;} assert(f() === 2) function f() {return 1;}");
        execjs.exec("function assert(b) {if (!b) throw 'error'} assert(f() === 1) var f = function() {return 2;} assert(f() === 2) function f() {return 1;}");
        fail();
    }catch(Exception e) {
        assertEquals("Error: error\n    at Object.<anonymous> (unknown source)\n    at Object.execjs.exec [as exec] (unknown source)\n    at org.jruby.ext.Readline.processLine (unknown source)\n    at org.jruby.ext.Readline.readline (unknown source)\n    at org.jruby.RubyIO.readline (unknown source)\n    at org.jruby.RubyKernel.gets (unknown source)\n    at org.jruby.RubyKernel.gets (unknown source