public void testBreakInFinally() {
    try {
        throw new Exception("throw me");
    } finally {
        break;
    }
    console.log("ok then...");
}
