public void testRandomStringUtils() {
    try {
        String universe = "";
        String result = RandomStringUtils.random(1, 0, 0, false, false, universe.toCharArray(), new Random());
        Assert.fail("Should have thrown an exception");
    } catch (Exception e) {
        Assert.assertTrue(e instanceof ArrayIndexOutOfBoundsException);
    }
}
