public void testIssue108() throws Exception {
    Object[] args = new Object[] {null};
    try {
        ClassUtils.toClass(args);
        fail("Should have thrown exception");
    } catch (NullPointerException e) {
    }
}
